project:
  type: website
  output-dir: docs

website:
  title: "Vasco Yasenov"
  site-url: "https://vyasenov.github.io/"
  description: "Personal Site of Vasco Yasenov"
  google-analytics: "G-RE2GPQMVXH"
  navbar:
    right:
      - text: About Me
        href: about.qmd
      - text: CV
        href: cv.qmd        
      - text: Blog
        href: blog/index.qmd        
      - text: Research
        href: research.qmd
      - text: Methods Map
        href: mind-map.qmd
      - text: Kids Books
        href: childrenbook.qmd
      - text: Software
        href: software.qmd                   
      - icon: github
        href: https://github.com/vyasenov
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/vasil-yasenov/
        target: _blank
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=pQw1oG8AAAAJ
        target: _blank
      - icon: amazon
        href: https://www.amazon.com/Causal-Inference-Toddlers-Meatball-Recipe/dp/B0BLG6SWZJ
        target: _blank
  search: true
  page-footer:
    left: "© 2025 Vasco Yasenov"
    right: "Powered by [Quarto](https://quarto.org)"

resources:
  - ../code/open-links-new-tab.js
  - ../code/back-to-top.js

format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: 
      - code/styles.css
    header-includes: |
      <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=680ee8d89f7a510019a96bcf&product=inline-share-buttons' async='async'></script>
      <script src="../code/open-links-new-tab.js"></script>  
      <script src="../code/back-to-top.js"></script>
      <link href="https://fonts.googleapis.com/css2?family=Fira+Code&family=Source+Code+Pro&display=swap" rel="stylesheet">
    toc: true
    page-layout: full
    includes: 
      after-body: 
        - ../_includes/comments.html
        - text: |
            <button id="back-to-top" onclick="scrollToTop()">↑</button>