// On each blog post, fetch the post index and inject up to 3 related posts,
// ranked by shared categories then by recency. Data file is generated by
// code/build-related.py and copied to docs/code/related-posts.json.

document.addEventListener("DOMContentLoaded", async function () {
    const path = location.pathname;
    const slug = path.split("/").pop().replace(/\.html$/, "");
    if (!slug || slug === "index") return;

    let posts;
    try {
        const resp = await fetch("../code/related-posts.json", { cache: "no-cache" });
        if (!resp.ok) return;
        posts = await resp.json();
    } catch (e) {
        return;
    }

    const current = posts.find(p => p.slug === slug);
    if (!current || !current.categories || !current.categories.length) return;

    const cats = new Set(current.categories);
    const related = posts
        .filter(p => p.slug !== slug)
        .map(p => ({
            ...p,
            shared: (p.categories || []).filter(c => cats.has(c)).length,
        }))
        .filter(p => p.shared > 0)
        .sort((a, b) => b.shared - a.shared || (a.date < b.date ? 1 : -1))
        .slice(0, 3);

    if (!related.length) return;

    const section = document.createElement("section");
    section.id = "related-posts";
    section.innerHTML =
        '<h2>Related posts</h2>' +
        '<ul class="related-posts-list">' +
        related.map(p => `<li><a href="${p.href}">${p.title}</a></li>`).join("") +
        '</ul>';

    // Append to #quarto-content (giscus is added asynchronously to the same parent
    // after page load, so the related-posts section will naturally render above it).
    const target = document.getElementById("quarto-content")
        || document.querySelector("main")
        || document.body;
    target.appendChild(section);
});
